### ISSUE TITLE
App crashes when trying to save text

### ISSUE THREAD

**Issue by Rilele** [lmj0011/save-on-device#9]
Thanks for this really useful app! But I encountered the following issue:
If I share some pain text and try to save it with this app into a file the app crashes with this stack trace:
```
FATAL EXCEPTION: main
Process: name.lmj001.savetodevice, PID: 8539
java.lang.RuntimeException: Unable to start activity ComponentInfo{name.lmj001.savetodevice/name.lmj001.saveondevice.MainActivity}: java.lang.NullPointerException: null cannot be cast to non-null type android.net.Uri
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: null cannot be cast to non-null type android.net.Uri
	at name.lmj001.saveondevice.MainActivity.onCreate(MainActivity.kt:52)
	at android.app.Activity.performCreate(Activity.java:8305)
	at android.app.Activity.performCreate(Activity.java:8284)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7872) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```
It seems the is no EXTRA_STREAM field in this case.

**Comment by lmj0011** [comment]
>**share some pain text** and try to **save it** with this app **into a file**

That is a feature this app doesn't support at the moment. Marking this as "wontfix" for now.

**Comment by lmj0011** [comment]
>If I share some pain text

@Rilele 

Are you sharing text from the clipboard? Or is this an actual `.txt` file you're trying to share?

**Comment by lmj0011** [comment]
@Rilele 

Ok, it seems you are attempting to share clipboard data, although I'm not 100% sure if the "selectable" text is coming from the clipboard when you select the `share` option from the context menu..

There's 2 ways I see this issue being resolved:

- enclosing these [lines](https://github.com/lmj0011/save-on-device/blob/v0.2.1/app/src/main/java/name/lmj001/saveondevice/MainActivity.kt#L50-L67) into a try/catch statement

- rewriting the `onCreate` function to take into consideration clipboard data and then somehow extracting it then saving it into a text file 

I'll leave this up for someone else willing to work on, since I don't have the time nor desire to patch, test, and submit a new app version to Google play at this time.
